name: Build Android app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: chmod +x ./gradlew

      - run: ./gradlew assembleDebug          public class MainActivity extends Activity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  TextView tv = new TextView(this);
                  tv.setText("Hello from GitHub Actions!");
                  setContentView(tv);
              }
          }
          EOF

      - run: gradle assembleDebug
